[package]
name = "risc0-js"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
risc0-zkvm = { version = "0.14", default-features = false, features = ["std"] }
