[package]
name = "risc0-js"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
bincode = "1.3"
risc0-zkvm = { version = "0.18.0", default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3"

