[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
bincode = "1.3.3"
bytemuck = "1.13.1"
methods = { path = "../methods" }
risc0-zkvm = { version = "0.18.0" }
serde = "1.0"
